name: Build WXT ZIP

on:
  push:

jobs:
  build-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build zip
        run: pnpm zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wxt-zip
          path: .output/*-chrome.zip
          if-no-files-found: error
